# name the compiler
!ifdef %HOME
!ifeq WATCOM9 yes
CC = c:\compil\watcom\bin\wcc386p
CL = c:\compil\watcom\binb\Wcl386
WL = c:\compil\watcom\binb\wlib
!else
CC = c:\compil\watcom10\binb\wcc386
CL = c:\compil\watcom10\binb\Wcl386
WL = c:\compil\watcom10\binb\wlib
!endif
!else
!ifeq WATCOM9 yes
CC = f:\compil\watcom\bin\wcc386p
CL = f:\compil\watcom\binb\Wcl386
WL = f:\compil\watcom\binb\wlib
!else
CC = f:\compil\watcom10\binb\wcc386
CL = f:\compil\watcom10\binb\Wcl386
WL = f:\compil\watcom10\binb\wlib
!endif
!endif

CC = wcc386
CL = Wcl386
WL = wlink
ASM = ml

!ifeq WATCOM9 yes
CFLAGS = /oeaxt /zp2 /4s /zq /v /s /DWATCOM9
# /d2
# /DTRACE
!else
CFLAGS = /onatx /oh /oi /ei /zp2 /6s /fp6 /s /wx /wcd=131 /wcd=202 /wcd=303 /wcd=308
!endif
AFLAGS = /Cx /c /W0 /Sa /DNoLanguage=SYSCALL /omf
LFLAGS  = option stack=7000
LFLAGS += system dos4g
# /d2
# /"OPTION SYMFILE=LBA.SYM OPTION MAP=LBA.MAP"

.SILENT

OBJECTS  = version.obj perso.obj object.obj global.obj
OBJECTS += flipbox.obj diskfunc.obj fiche.obj extra.obj incrust.obj
OBJECTS += grille.obj grille_a.obj func.obj cpymask.obj
OBJECTS += Message.obj ambiance.obj Balance.obj gamemenu.obj fire.obj
OBJECTS += geretrak.obj gerelife.obj
OBJECTS += HoloMap.obj playfla.obj adfli_a.obj mcga.obj
OBJECTS += msg_cust.obj

LIBS  = $(%LIB386_PATH)\LIB_3D\LIB_3D.LIB
LIBS += $(%LIB386_PATH)\LIB_CD\LIB_CD.LIB
LIBS += $(%LIB386_PATH)\LIB_MENU\LIB_MENU.LIB
LIBS += $(%LIB386_PATH)\LIB_MIDI\LIB_MIDI.LIB
LIBS += $(%LIB386_PATH)\LIB_MIX\LIB_MIX.LIB
LIBS += $(%LIB386_PATH)\LIB_SAMP\LIB_WAVE.LIB
LIBS += $(%LIB386_PATH)\LIB_SVGA\LIB_SVGA.LIB
LIBS += $(%LIB386_PATH)\LIB_SYS\LIB_SYS.LIB

EXE      = LBA0
# This is the GNU Make equivalent of CURDIR :=
CURDIR   = $+ $(%cdrive):$(%cwd) $-

$(EXE).exe: $(LIBS) $(OBJECTS)
	*$(WL) Name $@ $(LFLAGS) Library { $LIBS } File { $OBJECTS }

$(LIBS):
	cd $^:
	$(MAKE)
	@cd $(CURDIR)

.c.obj :
	PRNTITRE M "$*.C"
	$(CC) $^& $(CFLAGS)

.asm.obj :
	PRNTITRE M "$*.ASM"
	$(ASM) $(AFLAGS) $^&.ASM

clean: .SYMBOLIC
	@cd $(CURDIR)\..
	del /s /q *.obj
	del /s /q *.lib
	del /s /q *.err
	del /s /q *.ld
	del /s /q *.map
	del /s /q *.pch
	del /s /q *.lst
	del /s /q *.def
	@cd $(CURDIR)
