# name the compiler
!ifdef %HOME
!ifeq WATCOM9 yes
CC = c:\compil\watcom\bin\wcc386p
CL = c:\compil\watcom\binb\Wcl386
WL = c:\compil\watcom\binb\wlib
!else
CC = c:\compil\watcom10\binb\wcc386
CL = c:\compil\watcom10\binb\Wcl386
WL = c:\compil\watcom10\binb\wlib
!endif
!else
!ifeq WATCOM9 yes
CC = f:\compil\watcom\bin\wcc386p
CL = f:\compil\watcom\binb\Wcl386
WL = f:\compil\watcom\binb\wlib
!else
CC = f:\compil\watcom10\binb\wcc386
CL = f:\compil\watcom10\binb\Wcl386
WL = f:\compil\watcom10\binb\wlib
!endif
!endif

CC = wcc386
CL = Wcl386
WL = wlink
ASM = ml

!ifeq WATCOM9 yes
CFLAGS = /oeaxt /zp2 /4s /zq /v /s /DWATCOM9
# /d2
# /DTRACE
!else
CFLAGS = /onatx /oh /oi /ei /zp2 /6s /fp6 /s /wx /wcd=131 /wcd=202 /wcd=303 /wcd=308
!endif
AFLAGS = /Cx /Zm /c /W0 /Sa /DNoLanguage=SYSCALL /omf
# /d2
# /"OPTION SYMFILE=LBA.SYM OPTION MAP=LBA.MAP"

.SILENT

OBJETS1  = version.obj perso.obj object.obj global.obj
OBJETS2  = flipbox.obj diskfunc.obj fiche.obj extra.obj incrust.obj
OBJETS3  = grille.obj grille_a.obj func.obj cpymask.obj
OBJETS4  = Message.obj ambiance.obj Balance.obj gamemenu.obj fire.obj
OBJETS5  = geretrak.obj gerelife.obj
OBJETS6  = HoloMap.obj playfla.obj adfli_a.obj mcga.obj
OBJETS7  = msg_cust.obj

EXE      = LBA0

$(EXE).exe: LINK.LD
	$(WL) Name $@ @ $<

LINK.LD: $(OBJETS1) $(OBJETS2) $(OBJETS3) $(OBJETS4) $(OBJETS5) $(OBJETS6) $(OBJETS7)
	if exist $@ del $@
	echo option stack=7000 >> $@
	echo system dos4g >> $@
	for %%G in ($<) do echo File %%G >> $@
	echo Library %LIB386_PATH%\LIB_3D\LIB_3D.LIB >> $@
	echo Library %LIB386_PATH%\LIB_CD\LIB_CD.LIB >> $@
	echo Library %LIB386_PATH%\LIB_MENU\LIB_MENU.LIB >> $@
	echo Library %LIB386_PATH%\LIB_MIDI\LIB_MIDI.LIB >> $@
	echo Library %LIB386_PATH%\LIB_MIX\LIB_MIX.LIB >> $@
	echo Library %LIB386_PATH%\LIB_SAMP\LIB_WAVE.LIB >> $@
	echo Library %LIB386_PATH%\LIB_SVGA\LIB_SVGA.LIB >> $@
	echo Library %LIB386_PATH%\LIB_SYS\LIB_SYS.LIB >> $@

.c.obj :
	PRNTITRE M "$*.C"
	$(CC) $^& $(CFLAGS)

.asm.obj :
	PRNTITRE M "$*.ASM"
	$(ASM) $(AFLAGS) $^&.ASM
