# name the compiler
!ifdef %HOME
!ifeq WATCOM9 yes
CC = c:\compil\watcom\bin\wcc386p
WL = c:\compil\watcom\binb\wlib
!else
CC = c:\compil\watcom10\binb\wcc386
WL = c:\compil\watcom10\binb\wlib
!endif
!else
!ifeq WATCOM9 yes
CC = f:\compil\watcom\bin\wcc386p
WL = f:\compil\watcom\binb\wlib
!else
CC = f:\compil\watcom10\binb\wcc386
WL = f:\compil\watcom10\binb\wlib
!endif
!endif

CC = wcc386
WL = wlib
ASM = ml

!ifeq WATCOM9 yes
CFLAGS = /oeaxt /zp2 /4s /zq /s /DWATCOM9
!else
CFLAGS = /onatx /oh /oi /ei /zp2 /6s /fp6 /s /wx /wcd=131 /wcd=202 /wcd=303 /wcd=308
!endif
LFLAGS = /c /q /b /n
#AFLAGS = /m2 /mx /z /p /q /t /jMASM51 /jQUIRKS
AFLAGS = /Cx /c /W0 /Sa /DNoLanguage=SYSCALL /omf

.SILENT

OBJETS1  = BALANCE.obj DMA_CODE.obj N_WAVE.obj REAL.obj WAVE_A.obj WAVE_I.obj
OBJETS2  = GUS.obj

!ifeq WATCOM9 yes
LIB      = LB9_SAMP_DOS
!else
LIB      = LIB_SAMP_DOS
!endif

$(LIB).LIB: $(OBJETS1) $(OBJETS2)
	@echo $(OBJETS1) > clibmak.rsp
	@echo $(OBJETS2) >> clibmak.rsp

	@$(WL) $(LFLAGS) $(LIB) @clibmak.rsp
	@del clibmak.rsp

.c.obj :
	$(CC) $^& $(CFLAGS)

.asm.obj :
	$(ASM) $(AFLAGS) $^&.ASM
