
;-----------------------------------------------------------------------------
;				LIB_SYS.ASH
;-----------------------------------------------------------------------------

		extrn TimerRef:DWORD
		extrn NbFramePerSecond:WORD
		extrn WaitNbTicks:WORD
		extrn CmptFrame:WORD
		extrn Cmpt_18:WORD

;TIMERREF		equ	0
;NBFRAMEPERSECOND      	equ	4
;WAITNBTICKS		equ	6
;CMPTFRAME		equ	8
;CMPT_18		equ	10

;-----------------------------------------------------------------------------




